# Copyright (c) 2023, NVIDIA CORPORATION.

repos:
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        files: jupyterlab_nvdashboard/.*
        # Explicitly specify the pyproject.toml at the repo root, not per-project.
        args: ['--config', 'pyproject.toml']
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        files: jupyterlab_nvdashboard/.*$
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/rapidsai/dependency-file-generator
    rev: v1.20.2
    hooks:
      - id: rapids-dependency-file-generator
        args: ['--clean']
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.24.1
    hooks:
      - id: zizmor
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css]
        files: ^(src|style)/.*$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.0.0-rc.0
    hooks:
      - id: eslint
        files: ^src/.*\.(ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.36.0
          - eslint-config-prettier@8.8.0
          - eslint-plugin-prettier@5.0.0
          - prettier@3.0.0
          - '@typescript-eslint/eslint-plugin@6.1.0'
          - '@typescript-eslint/parser@6.1.0'
          - typescript@5.0.2
default_language_version:
  python: python3
