export const BAR_COLOR_LINEAR_RANGE: string[] = ['#ff7900', '#b30000'];
export const GPU_COLOR_CATEGORICAL_RANGE: string[] = ['#fecc5c', '#bd0026'];
export const PLUGIN_ID = 'jupyterlab-nvdashboard';
export const PLUGIN_ID_CONFIG = `${PLUGIN_ID}:config`;
export const PLUGIN_ID_OPEN_SETTINGS = `${PLUGIN_ID}:open-settings`;
export const WIDGET_TRACKER_NAME = 'gpu-dashboard-widgets';
export const COMMAND_OPEN_SETTINGS = 'settingeditor:open';
export const COMMAND_OPEN_WIDGET = 'gpu-dashboard-widget:open';
export const DEFAULT_UPDATE_FREQUENCY = 100; // ms
